// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cuel_mp_be.Database;

#nullable disable

namespace cuelmpbe.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Thai_100_CI_AS")
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("cuel_mp_be.Models.Allocation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Fte")
                        .HasColumnType("decimal(3, 2)")
                        .HasColumnName("fte");

                    b.Property<byte>("MonthNo")
                        .HasColumnType("tinyint")
                        .HasColumnName("month_no");

                    b.Property<int>("MpEmpId")
                        .HasColumnType("int")
                        .HasColumnName("mp_emp_id");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int")
                        .HasColumnName("project_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ProjectId" }, "IX_ALLOC_project");

                    b.HasIndex(new[] { "MpEmpId", "ProjectId", "MonthNo" }, "UQ_Allocations")
                        .IsUnique();

                    b.ToTable("Allocations");
                });

            modelBuilder.Entity("cuel_mp_be.Models.BudgetYear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CutoffDate")
                        .HasColumnType("date")
                        .HasColumnName("cutoff_date");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("description");

                    b.Property<string>("EmpListStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("emp_list_status")
                        .HasDefaultValueSql("('UNFROZEN')");

                    b.Property<DateTime?>("FrozenAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("frozen_at");

                    b.Property<string>("FrozenBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("frozen_by");

                    b.Property<DateTime?>("ReminderDate")
                        .HasColumnType("date")
                        .HasColumnName("reminder_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("('OPEN')");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("Year")
                        .HasColumnType("int")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Year" }, "UQ_BudgetYears_year")
                        .IsUnique();

                    b.ToTable("BudgetYears");
                });

            modelBuilder.Entity("cuel_mp_be.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DeptCode")
                        .HasColumnType("int")
                        .HasColumnName("dept_code");

                    b.Property<bool>("IsParent")
                        .HasColumnType("bit")
                        .HasColumnName("is_parent");

                    b.Property<int?>("ParentDeptId")
                        .HasColumnType("int")
                        .HasColumnName("parent_dept_id");

                    b.HasKey("Id");

                    b.HasIndex("ParentDeptId");

                    b.HasIndex(new[] { "DeptCode" }, "UQ_Departments_code")
                        .IsUnique();

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("cuel_mp_be.Models.DepartmentYear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AllocType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("alloc_type");

                    b.Property<string>("ApproverEmpNo")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("approver_emp_no");

                    b.Property<int>("BudgetYearId")
                        .HasColumnType("int")
                        .HasColumnName("budget_year_id");

                    b.Property<int>("DeptId")
                        .HasColumnType("int")
                        .HasColumnName("dept_id");

                    b.Property<string>("DeptName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("dept_name");

                    b.Property<string>("RequesterEmpNo")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("requester_emp_no");

                    b.Property<string>("ViewerEmpNo")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("viewer_emp_no");

                    b.HasKey("Id");

                    b.HasIndex("DeptId");

                    b.HasIndex(new[] { "BudgetYearId", "DeptId" }, "UQ_DepartmentYears")
                        .IsUnique();

                    b.ToTable("DepartmentYears");
                });

            modelBuilder.Entity("cuel_mp_be.Models.DeptGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("group_name");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "GroupName" }, "UQ_DeptGroups_name")
                        .IsUnique();

                    b.ToTable("DeptGroups");
                });

            modelBuilder.Entity("cuel_mp_be.Models.DeptGroupMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DeptId")
                        .HasColumnType("int")
                        .HasColumnName("dept_id");

                    b.Property<int>("GroupId")
                        .HasColumnType("int")
                        .HasColumnName("group_id");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex(new[] { "DeptId" }, "UQ_DGM_dept")
                        .IsUnique();

                    b.ToTable("DeptGroupMembers");
                });

            modelBuilder.Entity("cuel_mp_be.Models.DeptSubmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BudgetYearId")
                        .HasColumnType("int")
                        .HasColumnName("budget_year_id");

                    b.Property<int>("DeptId")
                        .HasColumnType("int")
                        .HasColumnName("dept_id");

                    b.Property<string>("RejectReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("reject_reason");

                    b.Property<string>("ReturnComment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("return_comment");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("('DRAFT')");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("submitted_at");

                    b.Property<string>("SubmittedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("submitted_by");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("verified_at");

                    b.Property<string>("VerifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("verified_by");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "BudgetYearId", "DeptId" }, "UQ_DeptSubmissions")
                        .IsUnique();

                    b.ToTable("DeptSubmissions");
                });

            modelBuilder.Entity("cuel_mp_be.Models.EmailLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BudgetYearId")
                        .HasColumnType("int")
                        .HasColumnName("budget_year_id");

                    b.Property<string>("CcAddr")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("cc_addr");

                    b.Property<int?>("DeptId")
                        .HasColumnType("int")
                        .HasColumnName("dept_id");

                    b.Property<DateTime>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("sent_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("subject");

                    b.Property<int?>("SubmissionId")
                        .HasColumnType("int")
                        .HasColumnName("submission_id");

                    b.Property<string>("Template")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("template");

                    b.Property<string>("ToAddr")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("to_addr");

                    b.HasKey("Id");

                    b.HasIndex("DeptId");

                    b.HasIndex("SubmissionId");

                    b.HasIndex(new[] { "BudgetYearId" }, "IX_EL_year");

                    b.ToTable("EmailLogs");
                });

            modelBuilder.Entity("cuel_mp_be.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DeptCode")
                        .HasColumnType("int")
                        .HasColumnName("dept_code");

                    b.Property<string>("EmpCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("emp_code");

                    b.Property<string>("EmpType")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("emp_type");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("full_name");

                    b.Property<DateTime>("LoadedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("loaded_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Location")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("location");

                    b.Property<string>("Position")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("position");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "EmpCode" }, "UQ_Employees_emp_code")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("cuel_mp_be.Models.GraphPriority", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BudgetYearId")
                        .HasColumnType("int")
                        .HasColumnName("budget_year_id");

                    b.Property<string>("ItemKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("item_key");

                    b.Property<string>("Panel")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("panel");

                    b.Property<int>("Priority")
                        .HasColumnType("int")
                        .HasColumnName("priority");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "BudgetYearId", "Panel", "ItemKey" }, "UQ_GP_item")
                        .IsUnique();

                    b.HasIndex(new[] { "BudgetYearId", "Panel", "Priority" }, "UQ_GP_priority")
                        .IsUnique();

                    b.ToTable("GraphPriorities");
                });

            modelBuilder.Entity("cuel_mp_be.Models.HrLoadAudit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BudgetYearId")
                        .HasColumnType("int")
                        .HasColumnName("budget_year_id");

                    b.Property<string>("ChangesJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("changes_json");

                    b.Property<DateTime>("LoadedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("loaded_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("LoadedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("loaded_by");

                    b.Property<int>("NewCount")
                        .HasColumnType("int")
                        .HasColumnName("new_count");

                    b.Property<int>("PrevCount")
                        .HasColumnType("int")
                        .HasColumnName("prev_count");

                    b.Property<string>("SnapshotJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("snapshot_json");

                    b.HasKey("Id");

                    b.HasIndex("BudgetYearId");

                    b.ToTable("HrLoadAudits");
                });

            modelBuilder.Entity("cuel_mp_be.Models.MpEmployee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AllocType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("alloc_type");

                    b.Property<int>("BudgetYearId")
                        .HasColumnType("int")
                        .HasColumnName("budget_year_id");

                    b.Property<int>("DeptId")
                        .HasColumnType("int")
                        .HasColumnName("dept_id");

                    b.Property<string>("EmpCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("emp_code");

                    b.Property<string>("EmpType")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("emp_type");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("full_name");

                    b.Property<string>("Location")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("location");

                    b.Property<DateTime?>("NewRequestDate")
                        .HasColumnType("date")
                        .HasColumnName("new_request_date");

                    b.Property<DateTime?>("PlannedResignDate")
                        .HasColumnType("date")
                        .HasColumnName("planned_resign_date");

                    b.Property<string>("Position")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("position");

                    b.Property<string>("RecordType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("record_type")
                        .HasDefaultValueSql("('ORIGINAL')");

                    b.Property<string>("RemarkDefault")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("remark_default");

                    b.Property<string>("RemarkOverride")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("remark_override");

                    b.Property<DateTime?>("ResignDate")
                        .HasColumnType("date")
                        .HasColumnName("resign_date");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<DateTime?>("TransferInDate")
                        .HasColumnType("date")
                        .HasColumnName("transfer_in_date");

                    b.Property<DateTime?>("TransferOutDate")
                        .HasColumnType("date")
                        .HasColumnName("transfer_out_date");

                    b.HasKey("Id");

                    b.HasIndex("DeptId");

                    b.HasIndex(new[] { "BudgetYearId", "DeptId" }, "IX_MPE_year_dept");

                    b.HasIndex(new[] { "BudgetYearId", "EmpCode", "RecordType" }, "UQ_MpEmployees")
                        .IsUnique();

                    b.ToTable("MpEmployees");
                });

            modelBuilder.Entity("cuel_mp_be.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BudgetYearId")
                        .HasColumnType("int")
                        .HasColumnName("budget_year_id");

                    b.Property<string>("Category")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("category");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit")
                        .HasColumnName("is_system");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("project_name");

                    b.Property<string>("Units")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("units");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "BudgetYearId", "ProjectName" }, "UQ_Projects_name")
                        .IsUnique();

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("cuel_mp_be.Models.ProjectScope", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("FinishDate")
                        .HasColumnType("date")
                        .HasColumnName("finish_date");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int")
                        .HasColumnName("project_id");

                    b.Property<string>("ScopeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("scope_name");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectScopes");
                });

            modelBuilder.Entity("cuel_mp_be.Models.StatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("action");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("actor");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("from_status");

                    b.Property<int>("SubmissionId")
                        .HasColumnType("int")
                        .HasColumnName("submission_id");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("to_status");

                    b.HasKey("Id");

                    b.HasIndex("SubmissionId");

                    b.ToTable("StatusHistories");
                });

            modelBuilder.Entity("cuel_mp_be.Models.Allocation", b =>
                {
                    b.HasOne("cuel_mp_be.Models.MpEmployee", "MpEmp")
                        .WithMany("Allocations")
                        .HasForeignKey("MpEmpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ALLOC_emp");

                    b.HasOne("cuel_mp_be.Models.Project", "Project")
                        .WithMany("Allocations")
                        .HasForeignKey("ProjectId")
                        .IsRequired()
                        .HasConstraintName("FK_ALLOC_project");

                    b.Navigation("MpEmp");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("cuel_mp_be.Models.Department", b =>
                {
                    b.HasOne("cuel_mp_be.Models.Department", "ParentDept")
                        .WithMany("InverseParentDept")
                        .HasForeignKey("ParentDeptId")
                        .HasConstraintName("FK_DEPT_parent");

                    b.Navigation("ParentDept");
                });

            modelBuilder.Entity("cuel_mp_be.Models.DepartmentYear", b =>
                {
                    b.HasOne("cuel_mp_be.Models.BudgetYear", "BudgetYear")
                        .WithMany("DepartmentYears")
                        .HasForeignKey("BudgetYearId")
                        .IsRequired()
                        .HasConstraintName("FK_DY_budget_year");

                    b.HasOne("cuel_mp_be.Models.Department", "Dept")
                        .WithMany("DepartmentYears")
                        .HasForeignKey("DeptId")
                        .IsRequired()
                        .HasConstraintName("FK_DY_dept");

                    b.Navigation("BudgetYear");

                    b.Navigation("Dept");
                });

            modelBuilder.Entity("cuel_mp_be.Models.DeptGroupMember", b =>
                {
                    b.HasOne("cuel_mp_be.Models.Department", "Dept")
                        .WithOne("DeptGroupMember")
                        .HasForeignKey("cuel_mp_be.Models.DeptGroupMember", "DeptId")
                        .IsRequired()
                        .HasConstraintName("FK_DGM_dept");

                    b.HasOne("cuel_mp_be.Models.DeptGroup", "Group")
                        .WithMany("DeptGroupMembers")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DGM_group");

                    b.Navigation("Dept");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("cuel_mp_be.Models.DeptSubmission", b =>
                {
                    b.HasOne("cuel_mp_be.Models.DepartmentYear", "DepartmentYear")
                        .WithOne("DeptSubmission")
                        .HasForeignKey("cuel_mp_be.Models.DeptSubmission", "BudgetYearId", "DeptId")
                        .HasPrincipalKey("cuel_mp_be.Models.DepartmentYear", "BudgetYearId", "DeptId")
                        .IsRequired()
                        .HasConstraintName("FK_SUB_dept_year");

                    b.Navigation("DepartmentYear");
                });

            modelBuilder.Entity("cuel_mp_be.Models.EmailLog", b =>
                {
                    b.HasOne("cuel_mp_be.Models.BudgetYear", "BudgetYear")
                        .WithMany("EmailLogs")
                        .HasForeignKey("BudgetYearId")
                        .HasConstraintName("FK_EL_budget_year");

                    b.HasOne("cuel_mp_be.Models.Department", "Dept")
                        .WithMany("EmailLogs")
                        .HasForeignKey("DeptId")
                        .HasConstraintName("FK_EL_dept");

                    b.HasOne("cuel_mp_be.Models.DeptSubmission", "Submission")
                        .WithMany("EmailLogs")
                        .HasForeignKey("SubmissionId")
                        .HasConstraintName("FK_EL_submission");

                    b.Navigation("BudgetYear");

                    b.Navigation("Dept");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("cuel_mp_be.Models.GraphPriority", b =>
                {
                    b.HasOne("cuel_mp_be.Models.BudgetYear", "BudgetYear")
                        .WithMany("GraphPriorities")
                        .HasForeignKey("BudgetYearId")
                        .IsRequired()
                        .HasConstraintName("FK_GP_budget_year");

                    b.Navigation("BudgetYear");
                });

            modelBuilder.Entity("cuel_mp_be.Models.HrLoadAudit", b =>
                {
                    b.HasOne("cuel_mp_be.Models.BudgetYear", "BudgetYear")
                        .WithMany("HrLoadAudits")
                        .HasForeignKey("BudgetYearId")
                        .IsRequired()
                        .HasConstraintName("FK_HLA_budget_year");

                    b.Navigation("BudgetYear");
                });

            modelBuilder.Entity("cuel_mp_be.Models.MpEmployee", b =>
                {
                    b.HasOne("cuel_mp_be.Models.BudgetYear", "BudgetYear")
                        .WithMany("MpEmployees")
                        .HasForeignKey("BudgetYearId")
                        .IsRequired()
                        .HasConstraintName("FK_MPE_budget_year");

                    b.HasOne("cuel_mp_be.Models.Department", "Dept")
                        .WithMany("MpEmployees")
                        .HasForeignKey("DeptId")
                        .IsRequired()
                        .HasConstraintName("FK_MPE_dept");

                    b.HasOne("cuel_mp_be.Models.DepartmentYear", "DepartmentYear")
                        .WithMany("MpEmployees")
                        .HasForeignKey("BudgetYearId", "DeptId")
                        .HasPrincipalKey("BudgetYearId", "DeptId")
                        .IsRequired()
                        .HasConstraintName("FK_MPE_dept_year");

                    b.Navigation("BudgetYear");

                    b.Navigation("DepartmentYear");

                    b.Navigation("Dept");
                });

            modelBuilder.Entity("cuel_mp_be.Models.Project", b =>
                {
                    b.HasOne("cuel_mp_be.Models.BudgetYear", "BudgetYear")
                        .WithMany("Projects")
                        .HasForeignKey("BudgetYearId")
                        .IsRequired()
                        .HasConstraintName("FK_PROJ_budget_year");

                    b.Navigation("BudgetYear");
                });

            modelBuilder.Entity("cuel_mp_be.Models.ProjectScope", b =>
                {
                    b.HasOne("cuel_mp_be.Models.Project", "Project")
                        .WithMany("ProjectScopes")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SCOPE_project");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("cuel_mp_be.Models.StatusHistory", b =>
                {
                    b.HasOne("cuel_mp_be.Models.DeptSubmission", "Submission")
                        .WithMany("StatusHistories")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SH_submission");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("cuel_mp_be.Models.BudgetYear", b =>
                {
                    b.Navigation("DepartmentYears");

                    b.Navigation("EmailLogs");

                    b.Navigation("GraphPriorities");

                    b.Navigation("HrLoadAudits");

                    b.Navigation("MpEmployees");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("cuel_mp_be.Models.Department", b =>
                {
                    b.Navigation("DepartmentYears");

                    b.Navigation("DeptGroupMember");

                    b.Navigation("EmailLogs");

                    b.Navigation("InverseParentDept");

                    b.Navigation("MpEmployees");
                });

            modelBuilder.Entity("cuel_mp_be.Models.DepartmentYear", b =>
                {
                    b.Navigation("DeptSubmission");

                    b.Navigation("MpEmployees");
                });

            modelBuilder.Entity("cuel_mp_be.Models.DeptGroup", b =>
                {
                    b.Navigation("DeptGroupMembers");
                });

            modelBuilder.Entity("cuel_mp_be.Models.DeptSubmission", b =>
                {
                    b.Navigation("EmailLogs");

                    b.Navigation("StatusHistories");
                });

            modelBuilder.Entity("cuel_mp_be.Models.MpEmployee", b =>
                {
                    b.Navigation("Allocations");
                });

            modelBuilder.Entity("cuel_mp_be.Models.Project", b =>
                {
                    b.Navigation("Allocations");

                    b.Navigation("ProjectScopes");
                });
#pragma warning restore 612, 618
        }
    }
}
